# Honours degree: Data science

## Assignment no. 1

### create a numpy array with random numbers

In [1]:
import numpy as np
a1=np.array([[12,20,32],[45,62,14],[77,34,19]])
a1

array([[12, 20, 32],
       [45, 62, 14],
       [77, 34, 19]])

### create 1Dim numpy array

In [2]:
a2=np.array([3,5,6,9])
a2

array([3, 5, 6, 9])

In [3]:
a2.ndim


1

### create 2D numpy array

In [4]:
a3=np.array([[32,15,64,29],[34,76,54,89]])
a3

array([[32, 15, 64, 29],
       [34, 76, 54, 89]])

In [5]:
a3.ndim


2

### create 3D array

In [6]:
a4=np.array([[[32,15,64,29],[34,76,54,89]],[[36,78,90,16],[36,75,67,23]]])
a4

array([[[32, 15, 64, 29],
        [34, 76, 54, 89]],

       [[36, 78, 90, 16],
        [36, 75, 67, 23]]])

In [7]:
a4.ndim

3

### Create numpy array with all 1's

In [8]:
a5=np.ones(6)
a5

array([1., 1., 1., 1., 1., 1.])

### Create numpy array with all 0's

In [9]:
a6=np.zeros(6)
a6

array([0., 0., 0., 0., 0., 0.])

### Create 4 x 5 numpy array with random elements

In [10]:
a7=np.array([[32,45,15,64,29],[34,65,76,54,89],[36,78,61,90,16],[28,79,48,21,98]])
a7

array([[32, 45, 15, 64, 29],
       [34, 65, 76, 54, 89],
       [36, 78, 61, 90, 16],
       [28, 79, 48, 21, 98]])

In [11]:
a7.shape

(4, 5)

### Apply basic math functions on  numpy array

In [12]:
arr=np.array([23,54,48,35,54,49])
arr

array([23, 54, 48, 35, 54, 49])

In [13]:
#sum
arr.sum()

263

In [14]:
#max
arr.max()

54

In [15]:
#min
arr.min()

23

In [16]:
#mean
arr.mean()

43.833333333333336

In [17]:
#std
arr.std()

11.275588183721899

In [18]:
#mode
# numpy dosen't have inbuilt mode function, so we need to import stats from scipy.
from scipy import stats
a=stats.mode(arr)
a

ModeResult(mode=array([54]), count=array([2]))

In [19]:
#size
arr.size

6

In [20]:
#shape
arr.shape

(6,)

In [21]:
#ndim
arr.ndim

1

In [22]:
#cumsum
np.cumsum(arr)

array([ 23,  77, 125, 160, 214, 263], dtype=int32)

In [23]:
#cumprod
np.cumprod(arr)

array([        23,       1242,      59616,    2086560,  112674240,
       1226070464], dtype=int32)

### problem

In [24]:
a =np.array([[3,1],[2,2]])
b =np.array([[0,1],[3,4]])


In [25]:
a+b

array([[3, 2],
       [5, 6]])

In [26]:
a-b

array([[ 3,  0],
       [-1, -2]])

In [27]:
a*b

array([[0, 1],
       [6, 8]])

In [28]:
a/b

C:\Users\SANJAY\AppData\Local\Temp/ipykernel_11740/1348051284.py:1: RuntimeWarning: divide by zero encountered in true_divide
  a/b


array([[       inf, 1.        ],
       [0.66666667, 0.5       ]])

In [29]:
a%b

C:\Users\SANJAY\AppData\Local\Temp/ipykernel_11740/1820107994.py:1: RuntimeWarning: divide by zero encountered in remainder
  a%b


array([[0, 0],
       [2, 2]], dtype=int32)

In [30]:
a**b

array([[ 1,  1],
       [ 8, 16]], dtype=int32)