# Data science library

- numpy
- pandas
- matplotlib

## Numpy

#### Numeric python/ Numerical Python

In [1]:
import numpy as np

In [2]:
np

<module 'numpy' from 'c:\\users\\sanjay\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\numpy\\__init__.py'>

### Numpy is used to create n dim arrays

In [3]:
np.array([10,20,30])

array([10, 20, 30])

In [4]:
a = np.array([10,20,30])

In [5]:
a

array([10, 20, 30])

In [6]:
#check type of a
type(a)

numpy.ndarray

In [7]:
#what is dim of a
a.ndim

1

In [8]:
#total no. elements present in a
a.size

3

In [9]:
a

array([10, 20, 30])

In [10]:
#python approach
len(a)

3

In [11]:
# find max
a.max()

30

In [12]:
#find min
a.min()

10

In [13]:
a

array([10, 20, 30])

In [14]:
#take average
60/3

20.0

In [15]:
a.mean()

20.0

In [16]:
# std deviation of array a
a.std()

8.16496580927726

In [17]:
# suppose i want to create an array with all zeros
z1 = np.zeros(6)
z1

array([0., 0., 0., 0., 0., 0.])

In [18]:
z1.ndim

1

In [19]:
z2 = np.zeros((4,4))# 4 rows and 4 columns
z2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
z2.ndim

2

In [21]:
z3 = np.zeros((2,2,2)) #2blocks, 2 rows, 2 columns
z3

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [22]:
z3.ndim

3

In [23]:
# create n dim array with all ones (1's)
np.ones(8)

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [24]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [25]:
# create an array with some diferent value
np.full((3,3),fill_value=100)

array([[100, 100, 100],
       [100, 100, 100],
       [100, 100, 100]])

In [26]:

np.full((3,2),fill_value=5)

array([[5, 5],
       [5, 5],
       [5, 5]])

In [27]:
# suppose we have list of different elements
#then how to create arrray
random = [12,34,-12,45,6,77,88,9,0,12,34,56,8,34,78]
random

[12, 34, -12, 45, 6, 77, 88, 9, 0, 12, 34, 56, 8, 34, 78]

In [28]:
len(random)

15

In [29]:
r = np.array(random)
r

array([ 12,  34, -12,  45,   6,  77,  88,   9,   0,  12,  34,  56,   8,
        34,  78])

In [30]:
r.min()

-12

In [31]:
r.mean()

32.06666666666667

In [32]:
r.ndim

1

In [33]:
r

array([ 12,  34, -12,  45,   6,  77,  88,   9,   0,  12,  34,  56,   8,
        34,  78])

### How to change dim of array

In [34]:
r

array([ 12,  34, -12,  45,   6,  77,  88,   9,   0,  12,  34,  56,   8,
        34,  78])

In [35]:
r.ndim

1

In [36]:
r.size

15

## use reshape

In [37]:
random = [12,34,-12,45,6,77,88,9,0,12,34,56,8,34,78]
r = np.array(random)
r.reshape(15,1)

array([[ 12],
       [ 34],
       [-12],
       [ 45],
       [  6],
       [ 77],
       [ 88],
       [  9],
       [  0],
       [ 12],
       [ 34],
       [ 56],
       [  8],
       [ 34],
       [ 78]])

In [38]:
r.reshape(1,15)

array([[ 12,  34, -12,  45,   6,  77,  88,   9,   0,  12,  34,  56,   8,
         34,  78]])

In [39]:
r.reshape(1,15).ndim

2

In [40]:
# multiples of 15: 5x3,3x5,1,15,15,1
r.reshape(5,3)

array([[ 12,  34, -12],
       [ 45,   6,  77],
       [ 88,   9,   0],
       [ 12,  34,  56],
       [  8,  34,  78]])

In [41]:
r.reshape(3,5)

array([[ 12,  34, -12,  45,   6],
       [ 77,  88,   9,   0,  12],
       [ 34,  56,   8,  34,  78]])

In [42]:
r

array([ 12,  34, -12,  45,   6,  77,  88,   9,   0,  12,  34,  56,   8,
        34,  78])

In [43]:
c = r.reshape(3,5)
c

array([[ 12,  34, -12,  45,   6],
       [ 77,  88,   9,   0,  12],
       [ 34,  56,   8,  34,  78]])

In [44]:
c.ndim

2

In [45]:
#how to check rows and columns
c.shape

(3, 5)

In [46]:
# If u want to trspose
c.T

array([[ 12,  77,  34],
       [ 34,  88,  56],
       [-12,   9,   8],
       [ 45,   0,  34],
       [  6,  12,  78]])

In [47]:
c

array([[ 12,  34, -12,  45,   6],
       [ 77,  88,   9,   0,  12],
       [ 34,  56,   8,  34,  78]])

In [48]:
np.transpose(c)

array([[ 12,  77,  34],
       [ 34,  88,  56],
       [-12,   9,   8],
       [ 45,   0,  34],
       [  6,  12,  78]])

In [49]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'Bytes0', 'CLIP', 'ComplexWarning', 'DataSource', 'Datetime64', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Str0', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'Uint64', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__getattr__', '__git_version__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__'

In [50]:
# if we want to check use of a function supported by numpy
help(np.transpose)


Help on function transpose in module numpy:

transpose(a, axes=None)
    Reverse or permute the axes of an array; returns the modified array.
    
    For an array a with two axes, transpose(a) gives the matrix transpose.
    
    Refer to `numpy.ndarray.transpose` for full documentation.
    
    Parameters
    ----------
    a : array_like
        Input array.
    axes : tuple or list of ints, optional
        If specified, it must be a tuple or list which contains a permutation of
        [0,1,..,N-1] where N is the number of axes of a.  The i'th axis of the
        returned array will correspond to the axis numbered ``axes[i]`` of the
        input.  If not specified, defaults to ``range(a.ndim)[::-1]``, which
        reverses the order of the axes.
    
    Returns
    -------
    p : ndarray
        `a` with its axes permuted.  A view is returned whenever
        possible.
    
    See Also
    --------
    ndarray.transpose : Equivalent method
    moveaxis
    argsort
    
    N